version: '3.8'

services:

  db-chat:
    container_name: db.chat
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: yii2-chat
      MYSQL_USER: yii2-chat
      MYSQL_PASSWORD: yii2-chat
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 13306:3306
    networks:
      - backend

  app-chat:
    container_name: app.chat
    image: yiisoftware/yii2-php:7.4-apache
    depends_on:
      - db-chat
    volumes:
      - ./:/app:delegated
    ports:
      - 8080:80
    networks:
      - backend

networks:
  backend: